### ISSUE TITLE
videos as images or actual videos 

### ISSUE THREAD

**Issue by mascazubi** [cunybpl/nycet_pnp#136]
We are using images that open up a video. It is not clear that the image is a video that can be clicked to play the video.

I see two ways we can make this clear:

1. modify all video images so that they all have a play button in the middle to prompt the user to click it.
2. use the actual video embed element on the page and [add the image as a video thumbnail in the youtube videos](https://support.google.com/youtube/answer/72431?hl=en&co=GENIE.Platform%3DAndroid)  

I recommend (2) because we can use the video embeds in other places and will already have the desired thumbnail if we add it to the video in youtube

**Comment by Sulaiman-Alam** [comment]
Would we be able to include both the images (but remove the videos from them), and include the embedded videos?

**Comment by mascazubi** [comment]
> Would we be able to include both the images (but remove the videos from them), and include the embedded videos?

@Sulaiman-Alam Not sure I follow, can you explain a bit more what you mean by including the images and the embedded videos?

**Comment by Sulaiman-Alam** [comment]
Sorry for the late reply, but I was thinking that maybe we can include the images and videos separately in the sites, (so maybe have figure 1 be the first image and figure 2 be the first vid...). But we can possibly discuss possible ways we can implement the images next week in the weekly meeting with Orlando, Farshad, and Lin to see what they think.

**Comment by mascazubi** [comment]
> Sorry for the late reply, but I was thinking that maybe we can include the images and videos separately in the sites, (so maybe have figure 1 be the first image and figure 2 be the first vid...). But we can possibly discuss possible ways we can implement the images next week in the weekly meeting with Orlando, Farshad, and Lin to see what they think.

@Sulaiman-Alam @SideSwipeX01 I think I  missed that meeting. Did you all talk about it? I still recommend step 2, it does not require creating additional images.

**Comment by Sulaiman-Alam** [comment]
@mascazubi I forgot to mention it in this past weekly meeting, so I'll make sure to mention it next week. But I agree that we can use the second method for the videos since it's really easy to embed youtube videos. We can ask the others on what they think.

**Comment by mascazubi** [comment]
[like]  Marco A Ascazubi reacted to your message:
________________________________
From: Sulaiman-Alam ***@***.***>
Sent: Thursday, May 23, 2024 6:31:59 PM
To: cunybpl/nycet_pnp ***@***.***>
Cc: Marco A Ascazubi ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [cunybpl/nycet_pnp] videos as images or actual videos (Issue #136)


@mascazubi<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mascazubi&d=DwMCaQ&c=4NmamNZG3KTnUCoC6InoLJ6KV1tbVKrkZXHRwtIMGmo&r=JhnGFrcQtyezV_XmUxJ5Fb9qa7BSPxtGS_YKlSrSOlw&m=x_dYASYt8_glq2mV412SLkzWeRQIVUab2AMMgy6uYdcHjWjGfI0Uka6_Iz2XYLRI&s=CEO1PO-w0f66-fcVaypZR_2hBvIU-YTNZ5i3UODYX64&e=> I forgot to mention it in this past weekly meeting, so I'll make sure to mention it next week. But I agree that we can use the second method for the videos since it's really easy to embed youtube videos. We can ask the others on what they think.

**Comment by Sulaiman-Alam** [comment]
- [ ] Include new excerpts for the pages given by Orlando
- [ ] Change all images linked to videos with images that have youtube icon on top
- [ ] Include any other bug or changes to MT pages
