### ISSUE TITLE
calculator download tables

### ISSUE THREAD

**Issue by mascazubi** [cunybpl/nycet_pnp#137]
we should move the calculator download links table (or replace the table with download cards) further down the page.
Starting the page showing the calculators and then the introduction feels awkward.

**Comment by Sulaiman-Alam** [comment]
Yup, we can move the introduction before the tables. And when it comes to organizing the calculators, I think having the cards would be useful. And we can possibly add a feature that when you click on a certain card it will not only download the calculator, but also go down to the appropriate equations. Just an idea of what we can do to improve the calculator pages.

**Comment by mascazubi** [comment]
thanks @Sulaiman-Alam the cards will allow the calculator download as well. Not sure about scrolling down at the same time though since for some people the download save file dialog would be triggered instead of automatically downloading the file

**Comment by Sulaiman-Alam** [comment]
Will also include updates to the calculation methodology formulas on this issue. 
![image](https://github.com/cunybpl/nycet_pnp/assets/108904299/20f0ad64-3f20-4eee-b2da-85cfcffdc64f)
