### ISSUE TITLE
clean up static folders

### ISSUE THREAD

**Issue by mascazubi** [cunybpl/nycet_pnp#145]
issue to track work on removing unused images.

@SideSwipeX01 please confirm which images need to be removed and @Sulaiman-Alam will remove them.

All placeholder images need to remain, @mascazubi to indicate which ones those are

**Comment by Sulaiman-Alam** [comment]
Will put a hold on this issue for now, since @SideSwipeX01 will be out until next Wednesday. So once he comes back, @Sulaiman-Alam will work with him to delete any images that aren't being used from the static files.

**Comment by Sulaiman-Alam** [comment]
In this branch, I'm still seeing the old content on my end. Even though I pushed the new content (the system images in branch 146). @mascazubi

**Comment by mascazubi** [comment]
Did you pull before making the changes?

**Comment by Sulaiman-Alam** [comment]
Yup, I made sure to pull the changed before starting to delete some of the unused files in the plant static folders.

**Comment by SideSwipeX01** [comment]
The [Air cooled chiller system](https://uat-pnp.nycenergytools.com/documents/systems/air-cooled-chiller/) figures on the web look smaller than all of the other system figures even though the files have the same dimensions. Any idea why ?

**Comment by mascazubi** [comment]
@SideSwipeX01 will take a look

**Comment by mascazubi** [comment]
> The [Air cooled chiller system](https://uat-pnp.nycenergytools.com/documents/systems/air-cooled-chiller/) figures on the web look smaller than all of the other system figures even though the files have the same dimensions. Any idea why ?

@SideSwipeX01 can you share a screen shot of what you are seeing? This is what I see:

![image](https://github.com/cunybpl/nycet_pnp/assets/5520163/190e97c5-38e0-4ebc-985f-4d6f33974d2c)

![image](https://github.com/cunybpl/nycet_pnp/assets/5520163/9133f0fe-73de-41b6-88ec-5762d66f0a5b)

Do you mean when it's blown up?

**Comment by mascazubi** [comment]
I think I resolved the issue. Main branch is behind right now so if you go to the live site, you will not see the new images. I also merged the changes @Sulaiman-Alam did from #146 into main and merged that into this issue branch #145.

@Sulaiman-Alam let's just confirm everything is good at 2pm and if so merge to main adn it will then be on the live site @SideSwipeX01
