### ISSUE TITLE
Upload the A-t-A HX calculation methodology and calculator

### ISSUE THREAD

**Issue by SideSwipeX01** [cunybpl/nycet_pnp#151]
Please focus on the system page images and the L-t-L HX page first.

This document was being vetted which is why it took so long to upload to the web. [Here is the link](https://www.dropbox.com/scl/fi/81emh17odld4m07cwlwub/2023_0705_PnP-CM-08_a2a_hx_calc_methodology.docx?rlkey=wrcpw4um2bygaswdp3q0wns62&dl=0), i will provide you with the figures next week.

**Comment by Sulaiman-Alam** [comment]
Be sure to add the figures to the page:
[figure 1](https://www.dropbox.com/scl/fi/r2vvw92i4x3cwtb6itaut/2024_0529_AtA-HX_figure-1.jpg?rlkey=665e9rxvkdfw76hibiusdoy87&dl=0)
[figure 2](https://www.dropbox.com/scl/fi/jz9u0puwdqyult6jt9o1v/2024_0529_AtA-HX_figure-2.jpg?rlkey=6lo2kypxega11w00j5dgv9jgd&dl=0)

**Comment by Sulaiman-Alam** [comment]
Here's the calculater for this page: [A-t-A calculator](https://www.dropbox.com/scl/fi/43a14npbkbrjav08k7xm0/2023_0706_PnP-EC-22_a2a_heat_exchanger.xlsx?rlkey=rlowegsqva5sh4rgnlp306kin&dl=0)
