### ISSUE TITLE
Modifications to the Component pages

### ISSUE THREAD

**Issue by SideSwipeX01** [cunybpl/nycet_pnp#169]
**CSCV fan and motor component page**

- [x] table 1,
     - [x] write out Air Handling Plant not AHU in the plant column,
     - [x] OAT should be written out fully Outdoor air temperature (F), last column
     - [x] WBT should be written out fully Wet-bulb temperature (F), last column
- [x] table 2
     - [x] change "Power draw of a CSCV fan motor" to "Electricity usage of CSCV fan motor (kWh)"
     - [x] Fan motor runtime (h) measurement, (h) should be (hours)
     - [x] write out Outdoor air temperature instead of OAT
     - [x] "Average hourly outside air temperature (OAT)" replace (OAT) with (F)
     - [x] add links to measurement pages
- [x] remove first sentence under Measurement Strategy section: "The measurement boundary for quantifying energy consumption for the CSCV fan and motor is shown in Figure 1 below."
- [x] remove last sentence under Measurement Strategy section: "Further details about measurement tools and equipment associated with measurements in Table 2 can be found here:"
- [x] move figure 1 under the 3 paragraphs in Measurement Strategy sections, want to show text first then figure
- [x] replace all instances of power draw or electric power draw with true RMS power

**Comment by SideSwipeX01** [comment]
**CSCV pump and motor component page**

- [ ] table 2
     - [ ] change "Power input to a constant-speed pump motor" to "Electricity usage of a CSCV pump motor"
     - [ ] remove "Non-weather dependent operating schedule for a constant-speed pump motor" cell and merge the two rows
     - [ ] add links to measurement pages (True RMS power should link to Electrical Spot Measurement page)
- [ ] **remove figure 1 and remove the sentence above it "The measurement boundary for quantifying energy consumption for the constant-speed pump and motor is shown in Figure 1 below."**
- [ ] rename figure 2 to figure 1
- [ ] replace the new figure 1 with[ this image](https://www.dropbox.com/scl/fi/0le34ylt5hg16qk5phq75/2024_0626_CSCV-pump-component_figure-1-01.jpg?rlkey=97vqcmqoo52f9283po5z990t9&dl=0)
- [ ] change the label of figure 1 to match the new image "measurement points of a cscv pump" or something along those lines

**Comment by SideSwipeX01** [comment]
**Liquid to Liquid HX component page**

- [ ] Table 1 is missing (F) in row 2, last column Blowdown water temperature
- [ ] Remove figure 1 from the Evaluation of Heat Transfer section
- [ ] add figure 1 ([file here](https://www.dropbox.com/scl/fi/th002aurmomq27f5qzjk3/2024_0625_LtL-HX-component_figure-1.jpg?rlkey=e1gjrozocn90ckoafguntdiyq&dl=0)) in the Measurement Strategy section
- [ ] In the measurement strategy section remove the sentence "Further information on pump flow measurement strategy can be found < here: Link to the pump flow content>."
- [ ] update the figure 1 label, make sure it doesn't say figure 2 anywhere in the page
- [ ] change green rectangle text to 'Liquid-to-Liquid Heat Transfer Calculations'

![image](https://github.com/cunybpl/nycet_pnp/assets/77025932/b74c22d4-ffe2-41d1-8740-dcb3156ba700)
![image](https://github.com/cunybpl/nycet_pnp/assets/77025932/31fc40d8-66dd-48ac-bb08-c981aa8af7cb)

**Comment by SideSwipeX01** [comment]
**Air to Air HX component page**

- [ ] in table 1 write out Outdoor air temperature (F) instead of OAT
- [ ] delete the first sentence under "Evaluation of Heat Transfer"
- [ ] in the Calculation Methodology section add the following sentence at the end of the paragraph and make it bold: "This methodology only applies to systems with rotary wheel heat exchangers"
- [ ] Update table 2 based on the screenshot below
- [ ] Update figure 1 with [this diagram](https://www.dropbox.com/scl/fi/rpj6wgkc6fhxs1bh3tgww/2024_0625_AtA-HX-component_figure-1.jpg?rlkey=xzynhoep81pbyjdy3cxa3ltcw&dl=0)
- [ ] Update figure 2 with [this diagram](https://www.dropbox.com/scl/fi/ec9antl6sjk1jskvycnlk/2024_0625_AtA-HX-component_figure-2.jpg?rlkey=x97at85k62qk9dsiz1xskpc5e&dl=0)
- [ ] make sure the labels of the figures are accurate
- [ ] change green rectangle text to 'Air-to-Air Heat Transfer Calculations'

![image](https://github.com/cunybpl/nycet_pnp/assets/77025932/b3a1931d-29a0-45ec-bf87-74eca5c2e653)
![image](https://github.com/cunybpl/nycet_pnp/assets/77025932/ec72a22e-cdd9-4833-ac6f-afb1beb0d004)

**Comment by SideSwipeX01** [comment]
**VSVV pump and motor component page**

- [ ] table 1 label should be "Plants and systems..." instead of "Plants systems"
- [ ] table 2
    - [ ] merge the first column of both rows, "Electricity input to a...." should appear once
    - [ ] write out Outdoor air temperature (F) in the measurement column
    - [ ] add links to the measurement pages (the first measurement should link to the True RMS Power page)
- [ ] in the Measurement Strategy section
    - [ ] remove the first sentence that mentions measurement boundary
    - [ ] remove the last sentence that references table 2
    - [ ] in the short paragraph that talks about the measurement strategy remove the part that says "average hourly motor speed and associated" it should say "and collect hourly OAT"
   - [ ] move figure 1 below the text
   - [ ] replace figure 1 with this image

**Comment by SideSwipeX01** [comment]
**VSVV fan and motor component page**

- [ ] table 1,
     - [ ] write out Air Handling Plant not AHU in the plant column,
- [ ] table 2
     - [ ] change "Electricity profile of a variable-...."" to "Electricity usage of VSVV fan motor (kWh)"
     - [ ] remove second row
     - [ ] Add a footnote to the second and third row, first column "Controlling variable, non-weather dependent" and "Controlling variable, weather dependent", the footnote should say something like "This variable should be measured to quantify the electricity usage of the VSVV fan if the operation is weather dependent" ("..is not weather dependent" for the second row variable)
     - [ ] add links to measurement pages
- [ ] in the Measurement Strategy section
     - [ ] remove the first sentence that mentions measurement boundary
     - [ ] remove the last sentence that references table 2
     - [ ] move figure 1 below the short paragraph (text first then figure)
     - [ ] label should be about VSVV fan not CSCV fan, also there are two labels here, remove the black one
     - [ ] new image in development

**Comment by Sulaiman-Alam** [comment]
Finished almost all of the updates, but there are a few notes:
- For VSVV fan and motor component page, there's an issue with the footnotes in the table (they're not showing entirely)
- I need figure 1 for VSVV pump and motor component page
- To change the green rectangle text for the calculation pages, I'll need to change their titles on their respective pages, so with that in mind, do we still change those texts?
- (Will also include uploading new thumbnail images on this update)

**Comment by SideSwipeX01** [comment]
Check COACHING > WEB DEMOS > WEB LAYOUT folder for the vsvv pump figure
