### ISSUE TITLE
reduce size of images

### ISSUE THREAD

**Issue by mascazubi** [cunybpl/nycet_pnp#190]
Look at all images being used for the site and make sure the file size is as small as possible. Some images have very large resolution and thus file size is excessive which causes them to render very slowly.

For example, the image in the lightning plant card on the home page: https://uat-pnp.nycenergytools.com/images/plants/lighting-plant/2024_0606_lighting%20plant_thumbnail.jpg

The space for the image is 274 x 467 pixels, and the current image is 2740 x 4760 pixels. The image is 10 time bigger than it needs to be.

Reduce size in:

- [x]  plant cards
- [x] system cards
- [x] component cards
- [x] measurement cards

Evaluate the sizes of guide content images to see if they are loading too slowly. These might need a different approach since we need to be able to zoom in on them

**Comment by Sulaiman-Alam** [comment]
Thumbnail Images that are too Big:

**Plant Pages**
- [ ] Air Handling Plant
- [ ] Hot Water Heating Plant 
- [ ] Lighting Plant 
- [ ] Water-cooled Chilled Water Plant _(Not as big as previous three)_

**System Pages**
- [ ] Air-cooled Chiller
- [ ] Air-to-air Energy Recovery _(Not as big)_
- [ ] Chilled Water Loop
- [ ] CSCV Air Handling Unit
- [ ] Electrical Distribution
- [ ] Hot Water Loop
- [ ] Lighting Fixture
- [ ] Steam Distribution
- [ ] VSVV Air Handling Unit
- [ ] Water-cooled Chiller

**Component Pages**
- [ ] Air-to-air Heat Exchanger
- [ ] CSCV Fan and Motor
- [ ] CSCV Pump and Motor
- [ ] VSVV Fan and Motor
- [ ] VSVV Pump and Motor

**System Pages** - _Might end up replacing down the line anyways so can ignore for this update if not needed_
- [ ] Water Flow Rate
- [ ] Relative Humidity
