### ISSUE TITLE
add excerpts to calculation content pages

### ISSUE THREAD

**Issue by mascazubi** [cunybpl/nycet_pnp#211]
make sure all calculation pages front matter has excerpt text like the [Air-to-air Heat Exchanger Heat Transfer Calculation Methodology and Calculator](https://uat-pnp.nycenergytools.com/documents/calculation-methodology/air-to-air-heat-exchanger-heat-transfer/)

the excerpt appears on the home page cards:
![image](https://github.com/user-attachments/assets/d01ec43f-8c2c-4c75-b6a4-cb25989e09dd)

**Comment by Sulaiman-Alam** [comment]
Excerpts found here: https://www.notion.so/nycsustainability/Update-excerpts-of-web-pages-d749b111624d402ea3c81067baecab75#9519ae9c5a7e41cb923537503af98d9a

Also rename the calculator pages using this notion page: https://www.notion.so/nycsustainability/Rename-Calculation-pages-to-the-following-107279213dc3800cb242e9bb05493dc8
