### ISSUE TITLE
Update the Motor Runtime Measurment Technique webpage

### ISSUE THREAD

**Issue by SideSwipeX01** [cunybpl/nycet_pnp#29]
https://www.dropbox.com/scl/fi/iykf8md9p2mko5bev549a/2023_1026_PnP-MT-04_motor_runtime_for_web.docx?rlkey=pzc5cv1pb0pk059seyvuwbq8r&dl=0

**Comment by Sulaiman-Alam** [comment]
Motor Runtime page has been updated with the videos and new image.

**Comment by Sulaiman-Alam** [comment]
Will circle back to this page at a later time.
