### ISSUE TITLE
Add VSVV pump and motor component content

### ISSUE THREAD

**Issue by Orlandolcx** [cunybpl/nycet_pnp#31]
dropbox link: https://www.dropbox.com/scl/fi/2fmcfjnjvs3ifynprxgv1/2022_0517_PnP-C-07_variable_pump_DEM.docx?rlkey=3a8pdmfat10rpy5sd5zm182cd&dl=0

**Comment by Sulaiman-Alam** [comment]
Finished uploading the page, waiting on figure 2 but otherwise the page is pretty much done.
