### ISSUE TITLE
Add hot water plant content

### ISSUE THREAD

**Issue by SideSwipeX01** [cunybpl/nycet_pnp#33]
https://www.dropbox.com/scl/fi/dwjeihp7iud4e2y3qzcs3/2022_0629_PnP-P-06_hot_water_plant_DEM.docx?rlkey=reax03yrnzt246leiy11twg7y&dl=0

upload this content on the web, use the HUGO files to create a new index card.

when you finish uploading the hot water heating plant, apply the same changes to the water cooled chilled water plant page. Orlando will include the[ word doc with changes](https://www.dropbox.com/scl/fi/9zliwd23bvq99r4x0ex7b/2023_1110_PnP-P-01_chilled_water_plant_WEB.docx?rlkey=t092g6wpqfeaj6af32cqu74w5&dl=0) for the water cooled chilled water plant.

**Comment by Sulaiman-Alam** [comment]
Hot Water Plant has been added, but not complete yet. Have to create the associated system pages and then incorporate them with the How Water Plant page
