### ISSUE TITLE
Upload MT-06, Outdoor Air Temp measurement technique on the web

### ISSUE THREAD

**Issue by SideSwipeX01** [cunybpl/nycet_pnp#56]
measurement technique is here: https://www.dropbox.com/scl/fi/exfrpb9g9ylz175pumfpx/2023_0627_PnP-MT-06_outdoor_air_temp_final_for_DEM.docx?rlkey=3j1fq7gd7ry1e6h7ap2zp0q46&dl=0

the video playlist for these logger is here: https://www.youtube.com/playlist?list=PL-NERcBsKg4Uo8mxaFa8glUd_X4-bd0R7

**Comment by Sulaiman-Alam** [comment]
Will also include the connections and updates for the system pages on this issue as well
