### ISSUE TITLE
Upload Water Pump Curve Measurement Technique

### ISSUE THREAD

**Issue by SideSwipeX01** [cunybpl/nycet_pnp#84]
https://www.dropbox.com/scl/fi/8a3ue61k5a02qh331yjlg/2023_0630_PnP-MT-12_water-pressure-and-pump-curve_-DEM.docx?rlkey=f1al7gz1dp3v0nxr50uxi50jr&dl=0

Please follow the same format that is on the web (videos, link to the equipment in the "Borrow Equipment" button, add numbers to the measurement steps, troubleshooting section, headers, etc.

**Comment by SideSwipeX01** [comment]
While you are at it please change the title name of "True RMS Power" to "Electrical Spot Measurement" and change the title "Electrical Energy" to "True RMS Power" for those two pages. We may need to slightly adjust the text within the pages but we can go through that together.

**Comment by mascazubi** [comment]
@Sulaiman-Alam has this been completed?

**Comment by Sulaiman-Alam** [comment]
@mascazubi yup this page has been uploaded 👍🏾

**Comment by Sulaiman-Alam** [comment]
@mascazubi I believe it was branch 94 since that branch also has the name updates for Electrical Spot Energy and True RMS Power

**Comment by mascazubi** [comment]
resolved via #94

**Comment by mascazubi** [comment]
resolved via #105
